# Generated by Django 4.2.2 on 2023-06-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=10)),
                ('fr', models.DateField()),
                ('to', models.DateField()),
                ('room', models.CharField(max_length=50)),
            ],
        ),
    ]
