# Generated by Django 4.2.2 on 2023-06-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='mobile_no',
        ),
    ]
