# Generated by Django 4.2.2 on 2023-06-22 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_info_fr_remove_info_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='room',
        ),
    ]
